steps:
- name: "gcr.io/cloud-builders/docker"
  args: ['build','-t','gcr.io/$PROJECT_ID/gcpdevops','.']

- name: "gcr.io/cloud-builders/docker"
  args: ["push","gcr.io/$PROJECT_ID/gcpdevops"]

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Project ID: $PROJECT_ID"
      docker build -t gcr.io/$PROJECT_ID/gcpdevops:latest .

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run 
  - --filename=deployment_gke.yaml
  - --image=gcr.io/devops-429410/gcpdevops:latest
  - --location=us-central-c
  - --cluster=gcp-devops-project
  - --namespace=gcp-devops-prod

options:
  logging: CLOUD_LOGGING_ONLY


